# Generated by Django 5.0.8 on 2024-08-18 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_catagory_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catagory",
            options={
                "verbose_name": "Inventory Catagory",
                "verbose_name_plural": "Catagories",
            },
        ),
        migrations.AlterField(
            model_name="catagory",
            name="name",
            field=models.CharField(
                help_text="Enter a Catagory    ", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="catagory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.catagory",
            ),
        ),
    ]
