# Generated by Django 5.0.8 on 2024-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_catagory_options_alter_catagory_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catagory",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
