# Generated by Django 5.0.8 on 2024-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="you can skip", null=True, unique=True
            ),
        ),
    ]
