# Generated by Django 5.0.8 on 2024-08-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_type",
                to="inventory.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seasonal_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.seasonalevents",
            ),
        ),
    ]
