# Generated by Django 5.0.8 on 2024-08-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_product_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.producttype",
            ),
        ),
    ]
